### ISSUE TITLE
what is the use of freezing the encoder ?

### ISSUE THREAD

**Issue by dingusagar** [qdrant/quaterion#169]
This is a basic doubt I got while reading the tutorials. We have encoder + head in the TrainableModel. Once the training is done, we use the encoder separately for inference.  If that is the case, what is the point of making the encoder params non-trainable? Or do we have to attach the head to the encoder during inference also?

Please point out the gap in my understanding. Thanks

**Comment by monatis** [comment]
Hi @dingusagar, thanks for asking!

During the inference, we use [SimilarityModel](https://quaterion-models.qdrant.tech/quaterion_models.model.html#quaterion_models.model.SimilarityModel) instance that is composed of an `Encoder` and an `EncoderHead`.
So if we choose to freeze `Encoder` then `EncoderHead` is still trainable to hopefully boost the performance as a part of our `SimilarityModel`.

**Comment by dingusagar** [comment]
Okay got it. I think I missed to read about SimilartyModel class in the docs. Thanks for the reply.
