### ISSUE TITLE
Support for Python 3.10+

### ISSUE THREAD

**Issue by jfelding** [qdrant/quaterion#214]
Is support for newer python versions planned?

**Comment by generall** [comment]
we are not actively maintaining this project

**Comment by jfelding** [comment]
Thanks

**Comment by simonhessner** [comment]
@generall This project is very interesting and I was wondering if you are planning to continue development at some point. Or if there are any active forks?

**Comment by joein** [comment]
Hello @simonhessner,

Unfortunately, we currently don't have such plans

**Comment by inspire22** [comment]
Dnag, sorry to hear that, this looks perfect for me.  For starting a new project, does it makes sense to try and get python10 working and still use this, or would anyone suggest an alternative?  Google doesn't work well with "quaterion alternatives' since it picks up the dataframe idea of the word.
